### PR TITLE
new comment block

### PR DESCRIPTION
**Pull request by Lionzee**
Added new comment block on the 3 file

### CODE REVIEW

**Review by JoaoDanielRufino — CHANGES_REQUESTED** [review]
Could you fix the tests and also add block comment to main.js file?

**Comment by Lionzee** [comment]
> Could you fix the tests and also add block comment to main.js file?

i make new fork, but idk why i didnt see main.js on the repo.

**Comment by Lionzee** [comment]
let me double check again.

**Review by JoaoDanielRufino — CHANGES_REQUESTED** [review]
@Lionzee Could you fix tests ?

**Comment by JoaoDanielRufino** [comment]
> > @Lionzee Could you fix tests ?
> 
> which one should i update?

The scanner tests, you need to fix the expected scan result. You could run the test locally or look at the failed action log to fix it

**Comment by JoaoDanielRufino** [comment]
Hi @Lionzee, are you still working on this PR ?

**Comment by JoaoDanielRufino** [comment]
Closing due inactivity

**Pull request closed without merging**
