### PR TITLE
add plaintext sample

### LINKED ISSUE #59: Add Plain Text code sample for tests
Add Plain Text code samples for tests on analyzer and scanner

### PR DESCRIPTION
**Pull request by Tashima42**
Added plain text Fernando Pessoa and Shakespeare poems to code samples

Closes #59

### CODE REVIEW

**Review by JoaoDanielRufino — CHANGES_REQUESTED** [review]
Hi, could you leave just one `.txt` file ?

**Review by JoaoDanielRufino — CHANGES_REQUESTED** [review]
Hi @Tashima42

Please, you also need to update `scanner_test.go`

**Comment by Tashima42** [comment]
Done, @JoaoDanielRufino

**Review by JoaoDanielRufino — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
